In [2]:
import pandas as pd 
import numpy as np 

In [3]:
df = pd.read_csv("Dataset_Fish.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [4]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
def cleaner(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="object":
                df[col].fillna(df[col].mode()[0], inplace=True)
            else:
                df[col].fillna(df[col].mean(), inplace=True)
    return df 

In [6]:
df = cleaner(df)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [8]:
def encodlash(df):
    from sklearn.preprocessing import LabelEncoder
    encoder = LabelEncoder()    
    for col in df.columns:
        if df[col].dtype=="object":
            if df[col].nunique()<=6:
                dummies = pd.get_dummies(df[col], prefix="col", dtype=int)
                df = pd.concat([df.drop(columns=col), dummies,], axis = 1)
            else:
                encoder = LabelEncoder()
                df[col] = encoder.fit_transform(df[col])
    return df 

In [9]:
df = encodlash(df)

In [10]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [11]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    int64  
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 8.8 KB


In [12]:
def scalinglash(df):
    from sklearn.preprocessing import StandardScaler
    standart_scaler = StandardScaler()
    num_col = df.select_dtypes(include=["float64", "int64"])
    df[num_col]= standart_scaler.fit_transform(df[num_col])
    return df

In [51]:
df = scalinglash(df)

ValueError: Boolean array expected for the condition, not int64

In [14]:
x = df.drop("Species", axis=1)
y = df['Species']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Algoritm Random Forest Regressor

In [17]:
from sklearn.ensemble import RandomForestRegressor
model_rf = RandomForestRegressor()

In [18]:
model_rf.fit(x_train, y_train)

RandomForestRegressor()

In [19]:
y_pred = model_rf.predict(x_test)
y_pred

array([2.54, 5.  , 2.96, 2.65, 3.24, 0.48, 5.  , 2.58, 2.5 , 2.97, 0.  ,
       1.46, 0.  , 1.81, 0.  , 0.08, 1.74, 2.44, 3.1 , 0.  , 5.  , 0.  ,
       0.  , 0.  , 0.1 , 1.78, 3.62, 2.66, 4.94, 5.  , 3.  , 2.43])

In [20]:
from sklearn.metrics import r2_score

In [22]:
score = r2_score(y_test, y_pred)
score

0.618687679344113

# Algoritm Decision Tree  Regressor

In [27]:
from sklearn.tree import  DecisionTreeRegressor
model_tree_reg = DecisionTreeRegressor()

In [28]:
model_tree_reg.fit(x_train, y_train)

DecisionTreeRegressor()

In [29]:
y_pred = model_tree_reg.predict(x_test)
y_pred

array([2., 5., 3., 2., 4., 0., 5., 2., 2., 3., 0., 0., 0., 1., 0., 0., 2.,
       2., 4., 0., 5., 0., 0., 0., 0., 2., 4., 2., 5., 5., 3., 4.])

In [30]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)
score

0.35868822591664773

# Algoritm KNN Regressor 

In [32]:
from sklearn.neighbors import  KNeighborsRegressor
model_KNN_Reg = KNeighborsRegressor(n_neighbors=5)

In [33]:
model_KNN_Reg.fit(x_train, y_train)

KNeighborsRegressor()

In [34]:
y_pred = model_KNN_Reg.predict(x_test)
y_pred

array([2.8, 5. , 2.6, 2.6, 2.8, 1.2, 5. , 2.6, 2.6, 1.6, 0.8, 1.2, 1. ,
       2.6, 1.2, 1.4, 1.2, 1.8, 1.8, 1.2, 5. , 1. , 1. , 1. , 1. , 1.6,
       3.4, 2.6, 4.4, 5. , 1.6, 2.6])

In [35]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)
score

0.47616488271464363

# Algoritm Linear Regressor

In [37]:
from sklearn.linear_model  import  LinearRegression
model_Lin_Reg= LinearRegression()

In [38]:
model_Lin_Reg.fit(x_train, y_train)

LinearRegression()

In [39]:
y_pred = model_Lin_Reg.predict(x_test)
y_pred

array([ 2.02867634,  4.07659202,  2.73907734,  1.87301027,  2.94455176,
       -1.3945635 ,  4.64564607,  3.32556051,  2.51796201,  2.56708231,
        1.28363156,  2.43090891,  0.32162802,  1.41004112, -0.51605712,
       -1.20693833,  2.13906108,  2.80374924,  1.7610617 ,  0.67579274,
        4.63773614, -0.27862496,  0.25795433,  1.16165672, -1.26065615,
        2.26335464,  2.35377658,  2.09247381,  4.56363344,  4.53421049,
        3.31090388,  2.82616129])

In [40]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)
score

0.5682035669605439