# USHBU AMALIYOTDA KNN VA SVM ALGORITMLARI ASOSIDA CLASSISFICATION MODELLAR QURAMIZ  

# Barcha kerakli kutubxonalarni  chaqirib olamiz 

In [6]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
from sklearn.preprocessing import StandardScaler
standart_scaler = StandardScaler()
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
model_SVC = SVC()
from sklearn.metrics import accuracy_score, r2_score
from sklearn.neighbors import KNeighborsClassifier
modelknnClas = KNeighborsClassifier(n_neighbors=5)
from sklearn.model_selection import cross_val_score, KFold

# DATA SETNI CHAQIRIB OLAMIZ 

In [7]:
df = pd.read_csv("heart.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [5]:
def cleaner(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtypr=="object":
                df[col].fillna(df[col].mode()[0], inplace=True)
            else:
                df[col].fillna(df[col].mean(), inplace=True)
    return df 

In [6]:
cleaner(df)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [8]:
def encodlash(df):    
    for col in df.columns:
        if df[col].dtype=="object":
            if df[col].nunique()<=6:
                dummies = pd.get_dummies(df[col], prefix="col", dtype=int)
                df = pd.concat([df.drop(columns=col), dummies,], axis = 1)
            else:
                encoder = LabelEncoder()
                df[col] = encoder.fit_transform(df[col])

    return df 

In [9]:
encodlash(df)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [11]:
def scalinglash(df):
    num_col = df.select_dtypes(include=["float64", "int64"]).columns.drop("target")
    df[num_col]= standart_scaler.fit_transform(df[num_col])
    return df

In [12]:
scalinglash(df)

age       sex        cp  trestbps      chol       fbs   restecg  \
0    -0.268437  0.661504 -0.915755 -0.377636 -0.659332 -0.418878  0.891255   
1    -0.158157  0.661504 -0.915755  0.479107 -0.833861  2.387330 -1.004049   
2     1.716595  0.661504 -0.915755  0.764688 -1.396233 -0.418878  0.891255   
3     0.724079  0.661504 -0.915755  0.936037 -0.833861 -0.418878  0.891255   
4     0.834359 -1.511706 -0.915755  0.364875  0.930822  2.387330  0.891255   
...        ...       ...       ...       ...       ...       ...       ...   
1020  0.503520  0.661504  0.055931  0.479107 -0.484803 -0.418878  0.891255   
1021  0.613800  0.661504 -0.915755 -0.377636  0.232705 -0.418878 -1.004049   
1022 -0.819834  0.661504 -0.915755 -1.234378  0.562371 -0.418878 -1.004049   
1023 -0.488996 -1.511706 -0.915755 -1.234378  0.155137 -0.418878 -1.004049   
1024 -0.047877  0.661504 -0.915755 -0.663216 -1.124743 -0.418878  0.891255   

       thalach     exang   oldpeak     slope        ca      thal  target  
0     0.821321 -0.712287 -0.060888  0.995433  1.209221  1.089852       0  
1     0.255968  1.403928  1.727137 -2.243675 -0.731971  1.089852       0  
2    -1.048692  1.403928  1.301417 -2.243675 -0.731971  1.089852       0  
3     0.516900 -0.712287 -0.912329  0.995433  0.238625  1.089852       0  
4    -1.874977 -0.712287  0.705408 -0.624121  2.179817 -0.522122       0  
...        ...       ...       ...       ...       ...       ...     ...  
1020  0.647366  1.403928 -0.912329  0.995433 -0.731971 -0.522122       1  
1021 -0.352873  1.403928  1.471705 -0.624121  0.238625  1.089852       0  
1022 -1.353113  1.403928 -0.060888 -0.624121  0.238625 -0.522122       0  
1023  0.429923 -0.712287 -0.912329  0.995433 -0.731971 -0.522122       1  
1024 -1.570556 -0.712287  0.279688 -0.624121  0.238625  1.089852       0  

[1025 rows x 14 columns]

In [13]:
x = df.drop("target", axis=1)
y = df['target']

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Algoritmimiz Support Vector Machine Classification 


In [15]:
model_SVC

SVC()

In [16]:
model_SVC.fit(x_train, y_train)

SVC()

In [17]:
y_pred = model_SVC.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0])

In [18]:
score = accuracy_score(y_test, y_pred)
score

0.8878048780487805

In [19]:
kn= KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model_SVC, x, y, cv=kn, scoring="accuracy")
print(scores)

[0.88780488 0.94634146 0.90731707 0.91707317 0.92195122]


In [20]:
print(np.mean(scores). round(2))

0.92


In [21]:
np.std(scores)

np.float64(0.019117968724161372)

# Xulosa SVC bo`yicha 
# Accuracy score = 0.889
# Scoring = 0.92 

# Algoritmimiz KNN Classification 

In [22]:
modelknnClas

KNeighborsClassifier()

In [23]:
modelknnClas.fit(x_train, y_train)

KNeighborsClassifier()

In [24]:
y_pred = modelknnClas.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1])

In [25]:
score = accuracy_score(y_test, y_pred)
score

0.8341463414634146

In [26]:
kn= KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(modelknnClas, x, y, cv=kn, scoring="accuracy")
print(scores)

[0.83414634 0.88780488 0.85365854 0.84878049 0.82439024]


In [27]:
print(np.mean(scores). round(2))

0.85


In [28]:
np.std(scores)

np.float64(0.021684010508188186)

# Xulosa KNN Classification bo`yicha 
# Accuracy score = 0.835
# Scoring = 0.85 

In [2]:
!pip install tabulate


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
from tabulate import tabulate

df_qisqa = df[["age", "sex", "chol", "thalach", "target"]].head(10)


tabulated = tabulate(df_qisqa, headers='keys', tablefmt='fancy_grid', showindex=False)
print(tabulated)

╒═══════╤═══════╤════════╤═══════════╤══════════╕
│   age │   sex │   chol │   thalach │   target │
╞═══════╪═══════╪════════╪═══════════╪══════════╡
│    52 │     1 │    212 │       168 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    53 │     1 │    203 │       155 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    70 │     1 │    174 │       125 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    61 │     1 │    203 │       161 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    62 │     0 │    294 │       106 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    58 │     0 │    248 │       122 │        1 │
├───────┼───────┼────────┼───────────┼──────────┤
│    58 │     1 │    318 │       140 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    55 │     1 │    289 │       145 │        0 │
├───────┼───────┼────────┼───────────┼──────────┤
│    46 │     1 │    249 │       144 │        0 │
